---
- name: Configure UFW
  hosts: all
  become: true
  tasks:
    - name: Allow SSH
      ufw:
        rule: allow
        port: ssh
        proto: tcp

    - name: Allow MySQL
      ufw:
        rule: allow
        port: 3306
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny 